# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='benurl',
            name='shortcode',
            field=models.CharField(default='cfedefaultshortcode', max_length=15),
            preserve_default=False,
        ),
    ]
