# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_benurl_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benurl',
            name='shortcode',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
